# Generated by Django 5.2.7 on 2025-11-10 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_alter_product_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="file",
            old_name="product_attribute",
            new_name="product_module",
        ),
        migrations.RenameField(
            model_name="image",
            old_name="product_attribute",
            new_name="product_module",
        ),
        migrations.RenameField(
            model_name="productgroup",
            old_name="product_attribute",
            new_name="product_module",
        ),
        migrations.RenameField(
            model_name="text",
            old_name="product_attribute",
            new_name="product_module",
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(
                blank=True, upload_to="products/files/%Y/%m/%d", verbose_name="فایل"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="products/images/%Y/%m/%d", verbose_name="تصویر"
            ),
        ),
        migrations.AlterField(
            model_name="text",
            name="text",
            field=models.TextField(blank=True, verbose_name="متن"),
        ),
        migrations.RenameModel(
            old_name="ProductAttribute",
            new_name="ProductModule",
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        upload_to="products/videos/%Y/%m/%d",
                        verbose_name="ویدیو",
                    ),
                ),
                (
                    "product_module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_related",
                        to="shop.productmodule",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
