# Generated by Django 5.2.7 on 2025-11-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_rename_product_attribute_file_product_module_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodule",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productmodule",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
