# Generated by Django 5.2.7 on 2025-11-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_productmodule_description_productmodule_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
