# Generated by Django 5.2.7 on 2025-11-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="province",
            field=models.CharField(default="tehran", max_length=50),
            preserve_default=False,
        ),
    ]
