# Generated by Django 5.2.7 on 2025-11-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_province"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
